# DEEP LEARNING
TUẦN 2 : NUMPY ,PANDAS,MATHPLOTLIB

# NUMPY 

In [3]:
# numpy là thư viện kiểu list
# vì 
#+ numpy nhanh
#+ có nhiều hàm tích hợp dễ sử dụng cho AI

# để sử dụng numpy thì : pip isnstall numpy
import numpy as np

In [4]:
#Thử tạo list

python_list = [1,2,3]

#chuyển đổi nhanh danh sachstreen thành numpy list

numpy_list = np.array(python_list)

type(numpy_list)

numpy.ndarray

In [5]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "Chào", True, 2.0]

In [6]:
my_list = [1, 2, 3, 4, 5]
np_list = np.array(my_list)
np_list

array([1, 2, 3, 4, 5])

In [9]:
# chuyển đỗi kiểu dữ liệu thì sao ?
np_list_int = np_list.astype(int)
np_list_int 

array([1, 2, 3, 4, 5])

In [12]:
# access và indexing 

x = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # x = np.array(range(1, 9))

In [13]:
# lấy sô 4 
x[3]

np.int64(4)

In [14]:
#lấy nhiều hơn 1 phần tử 
# công thức [start : and:step]
#lấy 1 2 3
x[0:3]

array([1, 2, 3])

In [ ]:
# lấy từ 3 - 8 theo 3 cách 
# Cách 1
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [16]:
# Cách 2 
x[2:]

array([3, 4, 5, 6, 7, 8])

In [ ]:
# Cách 3 không đúng 
x[2:-1] 

array([3, 4, 5, 6, 7, 8])

In [19]:
# lấy số 3 và số 5 

x[2],x[4]

(np.int64(3), np.int64(5))

In [20]:
# đặt danh sách các index muốn truy cập 

x[[2,4]]

array([3, 5])

In [21]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
# lấy số 2 
np_list[0,1] 

np.int64(2)

In [24]:
# lấy số 6
np_list[2,1]

np.int64(6)

In [25]:
# lấy [3,4], [5,6]
# Cách 1
np_list[1:, :]

array([[3, 4],
       [5, 6]])

In [26]:
# Cách 2
np_list[[1,2], :]


array([[3, 4],
       [5, 6]])

In [6]:
# Cách 3 
np_list[-2: ]

NameError: name 'np_list' is not defined

In [5]:
# lấy 1 3 5
np_list[:, 0]

NameError: name 'np_list' is not defined

In [4]:
# muốn lấy 1 và 5 theeo 2 cách
# Cách 1
np_list[[0,2], 0]
# Cách 2
np_list[0::2, 0]



NameError: name 'np_list' is not defined

In [3]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

np_list = np.array(x)
np_list

NameError: name 'np' is not defined

In [2]:
# lấy 2 6 10 14
np_list[:,1]    


NameError: name 'np_list' is not defined

In [1]:
# 16 15 14 13
np_list[3, ::-1]

NameError: name 'np_list' is not defined