# DEEP LEARNING
TUẦN 2 : NUMPY ,PANDAS,MATHPLOTLIB

# NUMPY 

In [1]:
# numpy là thư viện kiểu list
# vì 
#+ numpy nhanh
#+ có nhiều hàm tích hợp dễ sử dụng cho AI

# để sử dụng numpy thì : pip isnstall numpy
import numpy as np

In [2]:
#Thử tạo list

python_list = [1,2,3]

#chuyển đổi nhanh danh sachstreen thành numpy list

numpy_list = np.array(python_list)

type(numpy_list)

numpy.ndarray

In [3]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "Chào", True, 2.0]

In [4]:
my_list = [1, 2, 3, 4, 5]
np_list = np.array(my_list)
np_list

array([1, 2, 3, 4, 5])

In [5]:
# chuyển đỗi kiểu dữ liệu thì sao ?
np_list_int = np_list.astype(int)
np_list_int 

array([1, 2, 3, 4, 5])

In [6]:
# access và indexing 

x = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # x = np.array(range(1, 9))

In [7]:
# lấy sô 4 
x[3]

np.int64(4)

In [8]:
#lấy nhiều hơn 1 phần tử 
# công thức [start : and:step]
#lấy 1 2 3
x[0:3]

array([1, 2, 3])

In [9]:
# lấy từ 3 - 8 theo 3 cách 
# Cách 1
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [10]:
# Cách 2 
x[2:]

array([3, 4, 5, 6, 7, 8])

In [11]:
# Cách 3 không đúng 
x[2:-1] 

array([3, 4, 5, 6, 7])

In [12]:
# lấy số 3 và số 5 

x[2],x[4]

(np.int64(3), np.int64(5))

In [13]:
# đặt danh sách các index muốn truy cập 

x[[2,4]]

array([3, 5])

In [14]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
# lấy số 2 
np_list[0,1] 

np.int64(2)

In [16]:
# lấy số 6
np_list[2,1]

np.int64(6)

In [17]:
# lấy [3,4], [5,6]
# Cách 1
np_list[1:, :]

array([[3, 4],
       [5, 6]])

In [18]:
# Cách 2
np_list[[1,2], :]


array([[3, 4],
       [5, 6]])

In [19]:
# Cách 3 
np_list[-2: ]

array([[3, 4],
       [5, 6]])

In [20]:
# lấy 1 3 5
np_list[:, 0]

array([1, 3, 5])

In [21]:
# muốn lấy 1 và 5 theeo 2 cách
# Cách 1
np_list[[0,2], 0]
# Cách 2
np_list[0::2, 0]



array([1, 5])

In [22]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
# lấy 2 6 10 14
np_list[:,1]    


array([ 2,  6, 10, 14])

In [24]:
# 16 15 14 13
np_list[3, ::-1]

array([16, 15, 14, 13])

In [25]:
np_list[-1, -1::-1]


array([16, 15, 14, 13])

# BTVN thú vị

# cho ma trận = [[99,99,99],
                [99,99,99],
                [99,99,99]]

# hãy tưởng tượng ô 99 trống 
# giả sử  0 là o
# giả sử 1 là x
# lấy đầu vào từ phía x và phí o luôn phiên 
# Nếu đầu vào từ phía X là (0,0)
# ma trận sẽ trở thành 

# [x,99,99]
# [99,99,99]
# [99,99,99]
# nếu đầu vào từ phía o cũng là (0,0)
# thông báo nhập lại 
# nếu không thì điền vào ma trận

# thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dùng trò chơi


In [ ]:
a = [[99,99,99],[99,99,99],[99,99,99]]

def win(p):
    for i in range(3):
        if a[i][0]==a[i][1]==a[i][2]==p: return True
        if a[0][i]==a[1][i]==a[2][i]==p: return True
    if a[0][0]==a[1][1]==a[2][2]==p: return True
    if a[0][2]==a[1][1]==a[2][0]==p: return True
    return False

turn = 1  # 1 = X, 0 = O
while True:
    print(a)

    s = input(("X" if turn==1 else "O") + " nhập (row col): ").strip()
    s = s.replace("(", "").replace(")", "").replace(",", " ")
    parts = s.split()

    if len(parts) != 2:
        print("Nhập lại! Ví dụ: 0 0 hoặc 0,0")
        continue

    try:
        r, c = map(int, parts)
    except:
        print("Nhập lại! Chỉ nhập số.")
        continue

    if r < 0 or r > 2 or c < 0 or c > 2:
        print("Nhập lại! row, col chỉ từ 0 đến 2.")
        continue

    if a[r][c] != 99:
        print("Nhập lại! Ô đã có người đánh.")
        continue

    a[r][c] = turn

    if win(turn):
        print(a)
        print(("X" if turn==1 else "O"), "THẮNG!")
        break

    turn = 1 - turn


[[99, 99, 99], [99, 99, 99], [99, 99, 99]]
[[99, 1, 99], [99, 99, 99], [99, 99, 99]]
[[0, 1, 99], [99, 99, 99], [99, 99, 99]]
Nhập lại! Ví dụ: 0 0 hoặc 0,0
[[0, 1, 99], [99, 99, 99], [99, 99, 99]]
[[0, 1, 99], [99, 1, 99], [99, 99, 99]]
[[0, 1, 0], [99, 1, 99], [99, 99, 99]]
[[0, 1, 0], [99, 1, 99], [99, 1, 99]]
X THẮNG!


# BTVN 2
# cho y = [[1,2,3],[4,5,6],[7,8,9]]

# LẤY 4 5 6
# lấy 2, 5
# lấy 3,4
# lấy 9,6,3

In [1]:
y = [[1,2,3],
     [4,5,6],
     [7,8,9]]


In [3]:
# LẤY 4 5 6
print(y[1])   

[4, 5, 6]


In [ ]:
# Lấy 2 5
print(y[0][1], y[1][1])   # 2 5

2 5


In [ ]:
# Lấy 3 4 
print(y[0][2], y[1][0])   # 3 4

3 4


In [ ]:
# Lấy 9 6 3
print(y[2][2], y[1][2], y[0][2])   # 9 6 3

9 6 3


# BTVN 3

# cho x  = [[1,2,3,4,5,6,7,8,9,10]]

# xuata ra cas gias trị chẵn sử dụng if
# xuất ra các giá trị chẵn sử dụng lit comprehension
# 

In [7]:
x = [[1,2,3,4,5,6,7,8,9,10]]

In [8]:
for n in x[0]:
    if n % 2 == 0:
        print(n, end=" ")

2 4 6 8 10 

In [9]:
chan = [n for n in x[0] if n % 2 == 0]
print(chan)

[2, 4, 6, 8, 10]


# BTVN4
# tạo 1 mảng numpy có kích thức 150 x 5. giả sử mảng này chứa 150 mẫu dữ liệu 
# của sinh vienen  bao gồm chiều cao cân nặng tuổi , luonmgw và điểm trung bình
# tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cùng thành y
# tách mảng X thành X train X test trong đó X train chứa 70% dữ liệu và tahcs y thành y train và y test trong đó y train chứa 70% dữ leieuj
# tạo 10 tập dữ liệu không chồng chéo nhau

In [10]:
import numpy as np

np.random.seed(0)

data = np.zeros((150, 5))

# chiều cao, cân nặng, tuổi, lương, điểm TB
data[:, 0] = np.random.randint(150, 191, 150)              # cao (cm)
data[:, 1] = np.random.randint(45, 91, 150)                # nặng (kg)
data[:, 2] = np.random.randint(18, 26, 150)                # tuổi
data[:, 3] = np.random.randint(3, 51, 150)                 # lương (triệu)
data[:, 4] = np.round(np.random.uniform(0, 10, 150), 2)    # điểm TB

print(data.shape)
print(data[:5])


(150, 5)
[[150.    90.    22.    12.     8.21]
 [153.    56.    24.     3.     9.09]
 [153.    67.    18.    22.     8.16]
 [189.    58.    22.    39.     1.59]
 [159.    90.    25.    20.     6.29]]


In [12]:
X = data[:, :4]
y = data[:, 4]

print("X:", X.shape)
print("y:", y.shape)


X: (150, 4)
y: (150,)


In [13]:
idx = np.random.permutation(150)
train_size = int(0.7 * 150)

train_idx = idx[:train_size]
test_idx  = idx[train_size:]

X_train = X[train_idx]
X_test  = X[test_idx]

y_train = y[train_idx]
y_test  = y[test_idx]

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)


X_train: (105, 4)
X_test : (45, 4)
y_train: (105,)
y_test : (45,)


In [14]:
idx2 = np.random.permutation(150)
folds = np.array_split(idx2, 10)   # 10 tập, mỗi tập 15 mẫu

print("Số tập:", len(folds))
print("Số phần tử mỗi tập:", [len(f) for f in folds])


Số tập: 10
Số phần tử mỗi tập: [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]


In [15]:
X_fold1 = X[folds[0]]
y_fold1 = y[folds[0]]

print("X_fold1:", X_fold1.shape)
print("y_fold1:", y_fold1.shape)


X_fold1: (15, 4)
y_fold1: (15,)
